version: "3.9"

services:

  redis:
    container_name: redis
    image: redis
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save 60 1 --loglevel warning
    
  backend:
    build: .
    container_name: backend
    command: gunicorn core.wsgi --bind 0.0.0.0:8000
    volumes:
      - ./core:/app
      - static_volume:/app/static
      - media_volume:/app/meida
    expose:
      - "8000"
    environment:
      - SECRET_KET=test
      - DEBUG=False
    depends_on:
      - redis

  worker:
    build: .
    volumes:
      - ./core:/app
    command: celery -A core worker --loglevel=info
    depends_on:
      - redis
      - backend

  nginx:
    image: nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/home/app/static
      - media_volume:/home/app/media
    depends_on:
      - redis
      - backend
volumes:
  static_volume: 
  media_volume:
    