name: Django Project Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build Docker-compose
      run: docker-compose build .d
    - name: Run Docker
      run: docker exec backend sh -c "flake8 ."
